version: '3.9'

services:
  blacklist_db:
    image: postgres
    container_name: blacklist_db
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - blacklist_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
  
  blacklist:
    image: blacklist
    container_name: blacklist
    build:
      context: ./Blacklists
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: blacklist_db
      DB_PORT: 5432
      DB_NAME: user
      AUTH_TOKEN: qwertyuiopasdfghjklzxcvbnm123456
      NEW_RELIC_LICENSE_KEY: da9e5eddde8aa5cfdb21bc94f5cd50e7FFFFNRAL
    dns:
      - 8.8.8.8
    networks:
      - blacklist_net
      - app_net
    ports:
      - "3000:3000"
    depends_on:
      blacklist_db:
        condition: service_healthy

networks:
  app_net:
    name: app_net
    driver: bridge
  blacklist_net:
    name: blacklist_net
    driver: bridge